### ISSUE TITLE
hiiii there's a typo in one of your json files

### ISSUE THREAD

**Issue by playinful** [Sapphire645/DQB2ChunkEditorPlus#11]
in Tiles.json on line 5539 chalk is set to id 263 instead of 623

**Comment by Sapphire645** [comment]
Fixed! The issue had also been fixed on the new .txt files
[ed9697a](https://github.com/Sapphire645/DQB2ChunkEditorPlus/commit/ed9697a8e1bf7c7ba5b6185ef91001b81eb2259b)
